/**
 * Auxiliary data structures for mapping google cloud objects that belong to "argo-projects" bucket
 * https://cloud.google.com/storage/docs/json_api/v1/objects/list
 */
import { IGcObject } from "./gc-object";
import { IGcObjects } from "./gc-objects";

/**
 * Structures created/generated by backend service
 */
import { ICsvDataSource, EnumCsvDataSourceType } from "./csv-data-source";
import { IUnixValue, ITimeSeries } from "./date-time-value";
import { IListItem } from "./list-item";
import { IProject } from "./project";

export {
  IGcObject, 
  IGcObjects,
  ICsvDataSource,
  EnumCsvDataSourceType,
  IUnixValue,
  ITimeSeries,
  IListItem,
  IProject,
} 
