export const SELECT_PROJECT = 'SELECT_PROJECT';
export const PREDICTIONS_TAB_SELECTED_FLOW_CHANNEL_CHANGED = 'PREDICTIONS_TAB_SELECTED_FLOW_CHANNEL_CHANGED';
export const PREDICTIONS_TAB_SELECTED_DATE_CHANGED = 'PREDICTIONS_TAB_SELECTED_DATE_CHANGED';
export const PREDICTIONS_TAB_FETCH_DATA_STARTED = 'PREDICTIONS_TAB_FETCH_DATA_STARTED';
export const PREDICTIONS_TAB_FETCH_DATA_SUCCEEDED = 'PREDICTIONS_TAB_FETCH_DATA_SUCCEEDED';
export const PREDICTIONS_TAB_FETCH_DATA_FAILED = 'PREDICTIONS_TAB_FETCH_DATA_FAILED';